### ISSUE TITLE
mock popen kwarg executable typo

### ISSUE THREAD

**Issue by njoannin** [Simplistix/testfixtures#104]
Our unit tests fail when using testfixtures version 6.4.0 or 6.4.1: this is because a kwarg in testfixtures mock popen is spelled "executaable" instead of "executable".

Is that a purposeful change or a mistake?

**Comment by cjw296** [comment]
Looks like a typo. A PR with unit test and fix would be very welcome!

**Comment by njoannin** [comment]
Thanks for the fix.
I was trying to figure out how to build a unittest for this when you closed this issue (I don't think I would have managed).
Cheers
