### ISSUE TITLE
Can't use StringComparison with OutputCapture.compare

### ISSUE THREAD

**Issue by orenbenkiki** [Simplistix/testfixtures#106]
Since line 74 in `outputcapture.py` calls `_expected.strip`.

Possible fixes:

* Implement `strip` for `StringComparison` that just returns `self`.

* Modify line 74 to only strip actual strings.

Workaround for using current testfixtures:

* `StringComparison.strip = lambda self: self`

**Comment by cjw296** [comment]
This is what [`OutputCapture.captured`](https://testfixtures.readthedocs.io/en/latest/api.html#testfixtures.OutputCapture.captured) is for.
Hopefully that will be enough that you don't need `StringComparison` at all, but if you really must:

```python
compare(output.captured, expected=StringComparison('...'))
```
