### ISSUE TITLE
Expected MockPopen.set_command to accept a list

### ISSUE THREAD

**Issue by cblegare** [Simplistix/testfixtures#109]
Hi,

First, thank you for this great library!

I expected `MockPopen.set_command` to accept a list in the `command` argument the same way `Popen` does.  Am I missing something?

**Comment by cjw296** [comment]
Can you provided an example, including how you would expect it to behave and what currently happens?

**Comment by carthorse-cjw296** [comment]
@cblegare - it's been a couple of weeks, without further feedback it probably makes sense to close this issue...

**Comment by cjw296** [comment]
No followup.

**Comment by cblegare** [comment]
@cjw296 

Hello, sorry I missed the notification in all that spam.

From the [documentation of the subprocess module](https://docs.python.org/3/library/subprocess.html#frequently-used-arguments)
 
> args is required for all calls and should be a string, or a sequence of program arguments. Providing a sequence of arguments is generally preferred, as it allows the module to take care of any required escaping and quoting of arguments (e.g. to permit spaces in file names). If passing a single string, either shell must be True (see below) or else the string must simply name the program to be executed without specifying any arguments.

especially 

>  Providing a sequence of arguments is generally preferred

Here is an example:

```
the_command_to_be_run = [
    'ls',
    '-lah',
    r'some " wierd \FolDer NAME"'
]

mock.set_command(the_command_to_be_run)  # this should not raise IMO
```

The command is used as a dict key https://github.com/Simplistix/testfixtures/blob/master/testfixtures/popen.py#L226

So the fix is not trivial.

**Comment by cjw296** [comment]
Interestingly, `set_command` could be passed a string and still work fine in most cases where `Popen` was instantiated with a list, as I've made clear in https://github.com/Simplistix/testfixtures/commit/c0f48662bf6b36d148e18df66bc6896ffee93542.

However, I've also changed this process to be symmetric and robust in https://github.com/Simplistix/testfixtures/commit/80ca507bf39c2844e37d72ae5a8ec95bb0867ec7.

Both of these have been released in https://pypi.org/project/testfixtures/6.6.2/.

**Comment by cblegare** [comment]
Thanks, that should definetly do the trick!
