### ISSUE TITLE
"<BLANKLINE>" in examples

### ISSUE THREAD

**Issue by kannes** [Simplistix/testfixtures#111]
There are some "<BLANKLINE>" lines in https://testfixtures.readthedocs.io/en/latest/logging.html that actually should be blank lines.

**Comment by cjw296** [comment]
Can you explain the impact this is having for you?

**Comment by kannes** [comment]
Huh, Github stripped away the *thing*. Let's try that again!

The page has this block of example output:

```
Traceback (most recent call last):
 ...
AssertionError: sequence not as expected:
<BLANKLINE>
same:
(('root', 'INFO', 'a message'),)
<BLANKLINE>
expected:
(('root', 'ERROR', 'another error'),)
<BLANKLINE>
actual:
(('root', 'ERROR', 'an error'),)
```

while the actual output would be

```
AssertionError: sequence not as expected:

same:
(('root', 'INFO', 'a message'),)

expected:
(('root', 'ERROR', 'another error'),)

actual:
(('root', 'ERROR', 'an error'),)
```

This just confused me for a second or two.

**Comment by cjw296** [comment]
Okay, but can you explain what impact this is having for you?

I'm not sure there's a lot I can do, the examples in the documentation are tested with doctest and that requires the `<BLANKLINE>` stuff :-/

**Comment by kannes** [comment]
The impact is a mismatch between documentation and actual output. I was able to figure out that this was a formatting thing, someone else might not.

**Comment by cjw296** [comment]
Okay, like I said, unfortunately there's not a lot I can do to change this though.
If you can tell me how to change or configure doctest to not need the `<BLANKLINE>` stuff in it's example output, I'd love to make this change. I wonder if @tpeters has an opinion?
Unfortunately, in the meantime, there's not a lot I can do to fix this.
