### ISSUE TITLE
testfixtures.MockPopen does not work with list of "windows path"

### ISSUE THREAD

**Issue by fabiencelier** [Simplistix/testfixtures#119]
Python: 3.7 / 3.8
testfixtures: 6.10.1

I try to mock some system calls using testfixtures.MockPopen.
When mocking the calls with posix paths it works but with windows path (with "\") it fails when the args is an array. For some reason the path seems too escaped.

Here is an example to reproduce : 

```python
from testfixtures.popen import MockPopen
my_popen = MockPopen()
my_popen.set_command("C:\\path\\java -version", stderr="11.0.2")
my_popen("C:\\path\\java -version") # works
my_popen(["C:\\path\\java","-version"]) # fails
```
<pre>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fabien/.local/share/virtualenvs/tests-ais5CQRs/lib/python3.7/site-packages/testfixtures/popen.py", line 249, in __call__
    return MockPopenInstance(self, root_call, *args, **kw)
  File "/home/fabien/.local/share/virtualenvs/tests-ais5CQRs/lib/python3.7/site-packages/testfixtures/popen.py", line 79, in __init__
    raise KeyError('Nothing specified for command %r' % cmd)
KeyError: 'Nothing specified for command "\'C:\\\\path\\\\java\' -version"'
</pre>

**Comment by cjw296** [comment]
I'm afraid `MockPopen` doesn't currently support Windows. This is the code that's causing you issues: https://github.com/Simplistix/testfixtures/blob/master/testfixtures/popen.py#L12-L15

`pipes.quote` is `shlex.quote` in Py3.

I'd be happy to merge and release a PR that added support for Windows, but it'd need to have good test coverage for this and be sure to not negatively impact use on other operating systems.

Closing this until such a PR arrives.

**Comment by fabiencelier** [comment]
Ok I understand

Maybe it should be specified somewhere that it does not support windows then. 

I will have a look at it when I have time, but I think that CircleCI does not allow free builds with Windows. Github actions does.
