### ISSUE TITLE
Decimal comparison exposes Decimal type internals

### ISSUE THREAD

**Issue by asqui** [Simplistix/testfixtures#121]
Better late than never... just taking a much-overdue upgrade of testfixtures and I notice that changes in v6.0.0 (specifically, commit b1e79d7086714848cf8aa2f01d3c25587c01f788) change the output for `Decimal` comparisons.

Consider the following code:
```
from decimal import Decimal
from testfixtures import compare
compare({1: Decimal(0)}, {1: Decimal(1)})
```

In versions before 6.0.0, this produces the following output:
```
dict not as expected:

values differ:
1: Decimal('0') != Decimal('1')
````

After 6.0.0 under Python 2.7 (I know, I know) this begins to recurse into the internals of Decimal, and produces the following:
```
dict not as expected:

values differ:
1: Decimal('0') != Decimal('1')

While comparing [1]: Decimal not as expected:

attributes same:
['_exp', '_is_special', '_sign']

attributes differ:
'_int': '0' != '1'

While comparing [1]._int: '0' != '1'
```

Even in Python 3, however, the output gains some an extra couple of redundant lines:
```
 dict not as expected:

 values differ:
 1: Decimal('0') != Decimal('1')
+
+While comparing [1]: Decimal('0') != Decimal('1')
```

In our application, we are actually using `raises=False` and returning the diff message to users in some cases, so changing the format of this message is undesirable.

What is the recommended way to resolve this discrepancy when upgrading to 6.0.0+?

**Comment by asqui** [comment]
I can resolve both issues by registering a handler for the `Decimal` type:
```
import testfixtures.comparison
testfixtures.comparison.register(Decimal, testfixtures.comparison.compare_simple)
```

Would it be reasonable to have `compare_simple` be registered as the default handler for `Decimal`, since this type is in the standard library?

**Comment by cjw296** [comment]
Yep, that's what I was going to suggest. PR would be very welcome.
Make sure it works with both decimal and cDecimal on both py2 and py3 (not sure if there are import location differences...)
