### ISSUE TITLE
Comparison() objects no longer support comparison of properties (in all cases)

### ISSUE THREAD

**Issue by asqui** [Simplistix/testfixtures#122]
Again, a little late to the party but I think this is a change in behaviour from the 6.0.0 release.

Previously, it was possible to use `Comparison` to check the value of properties:
```
    class SomeClass(object):
        @property
        def prop(self):
            return ''
    
    compare(C(SomeClass, prop=''), SomeClass())
```

Now this fails with:
```
attributes in Comparison but not actual:
'prop': ''
```

I suspect this is a result of the following two changes in 6.0.0:
* compare() will now handle objects that do not natively support equality or inequality and will treat these objects as equal if they are of the same type and have the same attributes as found using vars() or __slots__. This is a change in behaviour which, while it could conceivably cause tests that are currently failing to pass, should not cause any currently passing tests to start failing.
* Changed the internals of ShouldRaise and Comparison to make use of compare() and so provide nested comparisons with better feedback. This finally allows ShouldRaise to deal with Django’s ValidationError.

Since `prop` is not in `vars()`, it is not discovered.

However, looking at the internals of `Comparison.__eq__` it appears that this behaviour varies depending on the `strict` setting:
```
# In testfixtures.comparison.Comparison.__eq__()
        if self.strict:
            v = _extract_attrs(other)  # Uses vars() or __slots__ as appropriate
        else:
            v = {}
            for k in self.v.keys():
                try:
                    v[k] = getattr(other, k)
                except AttributeError:
                    pass
```

So changing the example comparison above from:
`compare(C(SomeClass, prop=''), SomeClass())`
to:
`compare(C(SomeClass, strict=False, prop=''), SomeClass())`
causes the compare to pass once again.

So my suggested fix for consistent behaviour would be to follow-up the call to `_extract_attrs()` in the `Comparison.__eq__()` fragment above with an additional phase of attempting to extract extra attributes that are in `self.v.keys()` from `other` using `getattr()`.

Does that seem a reasonable approach for getting a behaviour that is (a) backward compatible with pre-6.0.0 and, perhaps more importantly, (b) treats properties consistently regardless of the `strict` setting?

**Comment by cjw296** [comment]
I think `strict` has a part in this; `strict=True` implies, in my head at least, "make sure everything matches up, based on attributes only" for Comparison objects and make sure "everything" matches when using `compare`. If adding `strict=False` "fixes" your use case, I'd suggest that might be the correct solution here.

That said, a good start, whatever way this pans out, is a PR with some tests that illustrate this behaviour, as it's evidently not covered by existing tests.

Then it might well just be a documentation issue to clarify what `Comparison(strict=True/False)` means further in the API docs, maybe additionally add an example for properties in the `Comparison` narrative docs?

**Comment by asqui** [comment]
The documentation talks about "attributes" in the general sense (i.e. including both data variables and properties):

> Another common problem with the checking in tests is that you may only want to make assertions about the type of an object that is nested in a data structure, or even just **compare a subset of an object’s _attributes_**. TextFixtures provides the Comparison class to help in situations like these.

> **If you only care about certain _attributes_**, this can also easily be achieved with the strict parameter:

And it was also my intuitive expectation that properties should be covered in both strict and non-strict modes (and additionally, this was also the behaviour pre-6.0.0).

I see the use of `vars()` (or `__slots__`) as  an implementation detail, so I think the proposed solution fits this model intuitively, without requiring any documentation updates.

Specifically, the proposed end-state I have in mind can be described as follows:-

`Compare` checks equality of the following:

1. The specified _data variables_ (or all data variables, if `strict=True`)
2. The specified _properties_
3. The specified _methods_

These are all true pre-6.0.0, whereas post-6.0.0, 2 and 3 are only true when `strict=False`.

1 is explicitly covered by the docs. 2 follows intuitively, and 3 is pathological enough that I don't think it deserves to be called out explicitly in the documentation, but should still be supported and covered in tests (technically methods are still instance attributes of a special sort, right?)

I'll prepare a PR on this basis...

**Comment by cjw296** [comment]
I'm not sure 2 follows intuitively, properties are as intuitive as methods for me: they're both callables, the former being descriptors. It may not have been clear before, and the implementation detail and lack of tests highlight this, but it was never my intention that properties should be included in `Comparison` checks.

I think you may be surprised by methods in Python 3 ;-)

That said, if you can get to your end-state stated above, without any grotesque changes to the code, I'd be happy to go with your suggestion.

**Comment by cjw296** [comment]
Can you make sure to add cases for the "not equal" path?

**Comment by asqui** [comment]
PR submitted. Hope it's not too grotesque.

Here's a couple of supporting branches that go back in time and cherry-pick just the tests from this PR to demonstrate that they were passing before b893d73:
* https://github.com/asqui/testfixtures/tree/%23122-tests-passing-before-6.0.0
* https://github.com/asqui/testfixtures/tree/%23122-tests-broken-by-refactor-in-6.0.0
