### ISSUE TITLE
Document and polish compare(x_label=..., y_label=...) args

### ISSUE THREAD

**Issue by asqui** [Simplistix/testfixtures#123]
It is currently possible to provide explicit labels for the values being compared by `compare()` like so:
```
compare('abc', 'def', x_label='current', y_label='previous')
```

This is handy particularly when you're using `compare(..., raises=False)` to construct a message explaining differences in production code.

This feature is currently not documented, and also does not work very smoothly. e.g. the natural usage would be to have `x`, `y`, `x_label`, and `y_label` as kwargs, however this does not currently work:
```
>>> testfixtures.compare(x='abc', y='def', x_label='current', y_label='previous')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ecn/users/rvdheide/source/ecn/source/python_3rd_party/testfixtures/comparison.py", line 606, in compare
    x, y = context.extract_args(args)
  File "/opt/ecn/users/rvdheide/source/ecn/source/python_3rd_party/testfixtures/comparison.py", line 464, in extract_args
    raise TypeError(message)
TypeError: Exactly two objects needed, you supplied: {'y': 'def', 'x': 'abc'}
```

Intuitively, I think of the following usage patterns for `compare()`:
* `compare('eks', 'why')`
* `compare('eks', expected='why')`
* `compare('eks', actual='why')`
* `compare(expected='eks', actual='why')`
* `compare(x='eks', y='why', x_label='X', y_label='Y')`

The following might be supported, but probably shouldn't be used:
* `compare(expected='eks', actual='why', x_label='X', y_label='Y')`

Does this seem a sensible proposition?

**Comment by cjw296** [comment]
Yep. Might be worthwhile starting to work on PRs for the issues you've already opened, rather than opening more ;-)
