### ISSUE TITLE
MockPopen() and universal_newlines=True

### ISSUE THREAD

**Issue by jedie** [Simplistix/testfixtures#127]
Seems it's not possible to use `MockPopen()` if `universal_newlines=True` is used:

I can only pass bytes to `stdout/stderr` in `Popen.set_command()` so that the call will get bytes. But with `universal_newlines=True` it should returned a string.

If i pass a string and not a byte, then a TypeError will be raised:

```
/lib/python3.6/site-packages/testfixtures/popen.py:94: TypeError:
        if stderr == STDOUT:
            line_iterator = chain.from_iterable(zip_longest(
                stdout_value.splitlines(True),
                stderr_value.splitlines(True)
            ))
>           stdout_value = b''.join(l for l in line_iterator if l)
E           TypeError: sequence item 0: expected a bytes-like object, str found
```

**Comment by cjw296** [comment]
What version of Python are you using?
Can you give me a complete unit test example as you'd like it to be?

**Comment by jedie** [comment]
Python 3.6 ... But no, i skipped the usage of testfixtures and used a other solution that will not mock the subprocess call. I have gone up a level and mocked the function that will create the subprocess call.

**Comment by cjw296** [comment]
You know `univeral_newslines` is deprecated, right? I think the new version is just a synonym in the form of `text=True`.

I'm going to see if I can add support for this without too much hassle.

**Comment by jedie** [comment]
> You know `univeral_newslines` is deprecated, right?

Yes, but `text` exists only with Python => v3.7 and i currently use 3.6

**Comment by cjw296** [comment]
Right, this is fixed in https://github.com/Simplistix/testfixtures/commit/174312bb2f82507d5eff6e126f520d94228d943c.

**Comment by cjw296** [comment]
Also in the latest release
