### ISSUE TITLE
DeprecationWarning: invalid escape sequence

### ISSUE THREAD

**Issue by llchan** [Simplistix/testfixtures#129]
There are some deprecation warnings about invalid escape sequences such as https://github.com/Simplistix/testfixtures/blob/51a4aaf1cd90e6e98650e660e6866c1fa28af866/testfixtures/comparison.py#L275

On a related note, should we enable warnings on CircleCI + perhaps even make them errors so we can catch these things early?

**Comment by cjw296** [comment]
Firstly, much like pictures of dogs, I will never not accept a pull request to fix deprecation warnings ;-) If they are an itch you'd like to scratch, I will be very happy to accept PRs that fix them!

However, [past](https://docs.python.org/3/library/unittest.html#deprecated-aliases) [and](https://docs.python.org/3.9/library/optparse.html) [recent](https://mail.python.org/archives/list/python-dev@python.org/thread/EYLXCGGJOUMZSE5X35ILW3UNTJM3MCRE/) experience has lead me to feel that chasing down and fixing deprecation warnings is not a fun or productive use of my free time. All the libraries I look after have tests that offer 100% line coverage, so as soon as things are *actually* removed (if they ever are...), they can be fixed right away.
