### ISSUE TITLE
compare() of Mock.call_args[_list] fails because these call() objects are two-tuples

### ISSUE THREAD

**Issue by asqui** [Simplistix/testfixtures#130]
Comparisons of `Mock.call_args` and `Mock.call_args_list` like these:
```
compare(mock.call_args, expected=call())
compare(mock.call_args_list, expected=[call()])
```

...fail with:
```
ValueError: need more than 2 values to unpack
```

...because (per the [mock documentation](https://docs.python.org/3/library/unittest.mock.html#calls-as-tuples))

> A call object is either a tuple of (positional args, keyword args) or (name, positional args, keyword args) depending on how it was constructed. When you construct them yourself this isn’t particularly interesting, but the call objects that are in the Mock.call_args, Mock.call_args_list and Mock.mock_calls attributes can be introspected to get at the individual arguments they contain.
> 
> The call objects in Mock.call_args and Mock.call_args_list are two-tuples of (positional args, keyword args) whereas the call objects in Mock.mock_calls, along with ones you construct yourself, are three-tuples of (name, positional args, keyword args).

...but `compare_call` assumes they are always three-tuples:

https://github.com/Simplistix/testfixtures/blob/aa22b5eb84addc9a90f6023c34377339e9c7f54c/testfixtures/comparison.py#L366-L370

NB: This codepath is short-circuited if the call objects compare equal with `==`, so this issue only arises in the event that they are not equal.

**Comment by asqui** [comment]
Here's a quick demonstration of the problem:

https://github.com/BATS/testfixtures/blob/4e6d3ee40acc9154b193cbfadda1e6b2857a0509/testfixtures/tests/test_mock.py#L44-L51

(Though I suspect this isn't where you want the test for this.)

**Comment by asqui** [comment]
See the commits in PR #131 for a couple of suggested variants on how to fix this.

**Comment by asqui** [comment]
PS: Who thought it was a good idea for `mock.call` objects to be tuple-like, with variable length! @voidspace :-p

**Comment by cjw296** [comment]
Don't be too quick to judge, I remember when @voidspace introduced `mock.call` and though the approach was a very graceful way of maintaining backwards compatibility.

`compare(mock.call_args, expected=call(...))` would be better as `mock.assert_called_with(...)`.

That said, I do think this is worth fixing.

**Comment by asqui** [comment]
No judgement at all. That was just a tongue-in-cheek excuse to namedrop Michael into the conversation; I know that evolution of public APIs is an extremely difficult task!

Agree that `mock.assert_called_with(...)` is more appropriate if you only care about the last call. In practice we generally always `compare(mock.call_args_list, expected=[call(...), ...]` to capture all calls (in particular, any extra calls that you weren't expecting).

**Comment by cjw296** [comment]
I'd suggest `compare(mock.mock_calls, expected=[call(...), ...]` as a more paranoid approach. 
Also doesn't tickle the bug in this issue ;-)
