### ISSUE TITLE
compare() gives misleading error messages when comparing mock calls to tuples

### ISSUE THREAD

**Issue by asqui** [Simplistix/testfixtures#132]
`mock.call` objects are technically tuples of `(<optional_name_str>, args_tuple, kwargs_dict)` and they support comparison to tuples of length zero, one, two (containing any combination of the three items), or three, items.

This is documented in the (unpublished) [docstring for `_Call`](https://github.com/python/cpython/blob/0d12672b30b8c6c992bef7564581117ae83e11ad/Lib/unittest/mock.py#L1993), which isn't rendered in the generated docs...

This looks like a historic feature to allow comparison to naked tuples before `call` was, um, callable...

So it is technically possible for one to write arcane call assertions like this:
```
compare(mock.call_args, expected=((1,),))  # Rather than expected=call(1)
compare(mock.call_args, expected=('', (1,),))  # Rather than expected=call(1)
compare(mock.call_args, expected=({'x': 1},))  # Rather than expected=call(x=1)
compare(mock.call_args, expected=('', {'x': 1},))  # Rather than expected=call(x=1)
compare(mock.foo.mock_calls, expected=[('foo', {'x': 1},)])  # Rather than expected=[call.foo(x=1)]
# ...etc...
```

These will work ok as long as the assertions pass, but when they fail, will produce horribly misleading output like this:
```
>       compare(m.foo.mock_calls, [('bar', dict(x=2))])
E       AssertionError: sequence not as expected:
E       
E       same:
E       []
E       
E       first:
E       [call.bar(x=1)]
E       
E       second:
E       [('bar', {'x': 2})]
E       
E       While comparing [0]: sequence not as expected:
E       
E       same:
E       ('bar',)
E       
E       first:
E       ((), {'x': 1})
E       
E       second:
E       ({'x': 2},)
E       
E       While comparing [0][1]: () != {'x': 2}
```

Rather than the much more meaningful result you would get by using `call()`:
```
>       compare(m.foo.mock_calls, [call.bar(x=2)])
E       AssertionError: sequence not as expected:
E       
E       same:
E       []
E       
E       first:
E       [call.bar(x=1)]
E       
E       second:
E       [call.bar(x=2)]
E       
E       While comparing [0]: 
E       'call.bar(x=1)'
E       !=
E       'call.bar(x=2)'
```

I got into this tangent when digging into #130 so I wanted to raise a separate issue to document this...

Do we care about producing more helpful error output if people write arcane comparisons like this?

I'm inclined to say no... if you like to write unreadable assertions like that, then you should enjoy the unreadable comparison failure messages that they will result in! :-)

**Comment by cjw296** [comment]
I don't believe the output is horribly misleading, read top-down it's pretty clear. Bottom up, if it's confusing, you read up until it isn't. Given this is the failure case, and an obscure one at that, I don't think it's worth worrying about this.
