### ISSUE TITLE
Decorator for OutputCapture

### ISSUE THREAD

**Issue by bryceschober** [Simplistix/testfixtures#153]
It would be nice to have a decorator for OutputCapture. It seems odd to not have one when LogCapture does, but probably just an artifact of history...

**Comment by cjw296** [comment]
It wouldn't really work, I'm afraid. You can't make assertions about the content until the streams are closed, and with a decorator, that couldn't happen until the test was over.

If you can find a way to make it work, feel free to chuck in a PR, but it's not something I'll be working on.
