### ISSUE TITLE
OuputCapture.compare() doesn't support StringComparison

### ISSUE THREAD

**Issue by bryceschober** [Simplistix/testfixtures#154]
It seems to me that `OutputCapture.compare()` doesn't support `StringComparison`:
```
Traceback (most recent call last):
  File "...", line 251, in test_...
    output.compare(
  File ".../lib/python3.8/site-packages/testfixtures/outputcapture.py", line 127, in compare
    _expected = _expected.strip()
AttributeError: 'StringComparison' object has no attribute 'strip'
```

**Comment by cjw296** [comment]
This is a bit of an edge case, you can do one of two things:

- `compare(output.captured, expected=S(...)`
- pass `strip_whitespace=False` to the `OutputCapture` constructor.
