### ISSUE TITLE
LogCapture does not preserve/restore filters

### ISSUE THREAD

**Issue by rittneje** [simplistix/testfixtures#157]
https://github.com/Simplistix/testfixtures/blob/2e80aca186569cd787512eab643dbf35b14ad02a/testfixtures/logcapture.py#L147-L157

https://github.com/Simplistix/testfixtures/blob/2e80aca186569cd787512eab643dbf35b14ad02a/testfixtures/logcapture.py#L173-L178

It seems that any filters added via [`Logger.addFilter`](https://docs.python.org/3/library/logging.html#logging.Logger.addFilter) are not preserved or restored. Is this intentional?

**Comment by cjw296** [comment]
No, not intentional, but filters are a very rarely used feature so no-one has noticed in the last decade or so ;-)
PR, including tests, to verify would be very welcome.
