### ISSUE TITLE
Package does not specify supported Python versions

### ISSUE THREAD

**Issue by andy-maier** [simplistix/testfixtures#171]
The testfixtures package does not specify the supported Python versions in a way so that Pip understands it. This causes pip to install testfixtures on Python versions it does not support. 

This lack of Python version specification did not cause problems for us before testfixtures version 6.18.4, but that version introduced a new check that fails on Python 3.5, and `pip install testfixtures` on Python 3.5 happily installs the latest available version 6.18.5 due to the missing Python version specification, and thus runs into the new check failing.
For details, see [this test run](https://github.com/pywbem/pywbem/runs/5347731908?check_suite_focus=true).

I suggest that testfixtures specifies the supported Python versions using the `python_requires` argument to `setup()`, e.g.

```
setup():
    ...
    python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*',
    ...
)
```

**Comment by cjw296** [comment]
Hi Andy, I'm afraid Python 3.5 was EOL over 2yrs ago now, and I'm working on testfixtures v7 which will target Python 3.6 as a minimum. 

What's stopping you upgrading to a supported version of Python 3?

**Comment by andy-maier** [comment]
This issue is not about not supporting Python 3.5, it is about provoking the next problem once you remove support for another Python version.

**Comment by cjw296** [comment]
That's taken care of in the [v7 branch](https://github.com/cjw296/testfixtures/blob/v7/setup.py#L42).
It's a shame you haven't actually stated the error you've seen, I suspect it may be a case of needing a newer version of the mock backport, although I think that may already only support python 3.6.

Again, what's stopping you upgrading to a supported version of Python 3?

**Comment by andy-maier** [comment]
What is stopping us from dropping support for Python 3.5 is that as of today RedHat still supports it in some versions of RHEL. So "unsupported" is relative, the PSF has stopped support, but RHEL still supports it. And I did not do the research to find out who else besides the PSF still supports Python 3.5.

So far we did not need the mock backport, and testfixtures also did not insist on it, that's why it is not in our dependency list at all so far. And for an old version sch as Python 3.5 I considered it an adequate solution to pin testfixtures to <6.4.0.

Again, this issue is not about 3.5 support. It is about the fact that the testfixtures package does not declare the Python versions it supports. That causes pip to install testfixtures versions 6.4.0 to 6.18.5 happily on Python 3.5. And again, I did not ask for fixing that for Python 3.5, but I'm asking to be prepared for the future when you remove for example the equally unsupported version 2.7 and still allow pip to install on Python 2.7.

By not declaring the supported Python versions in a way that pip understands, you are putting the burden on your users. And the effort to fix that is just the one argument I mentioned above. That is way less effort than the amount of text you and I have written on this meanwhile.

You can do what you want of course.
