### ISSUE TITLE
Latest version broke our pipeline

### ISSUE THREAD

**Issue by screig** [simplistix/testfixtures#173]
From pip list...

testfixtures                  6.18.5

============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-7.0.1, pluggy-1.0.0

Hint: make sure your test modules/packages have valid Python names.
Traceback:
C:\Python36\lib\importlib\__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
panormus\test\test_utils.py:11: in <module>
    from testfixtures import LogCapture
venv\lib\site-packages\testfixtures\__init__.py:13: in <module>
    from testfixtures.comparison import (
venv\lib\site-packages\testfixtures\comparison.py:14: in <module>
    from testfixtures.mock import parent_name, mock_call, unittest_mock_call
venv\lib\site-packages\testfixtures\mock.py:47: in <module>
    sys.version_info, backport_version
E   ImportError: Please upgrade Python (you have sys.version_info(major=3, minor=6, micro=6, releaselevel='final', serial=0)) or Mock Backport (You have None)

**previously:**

From pip list...

testfixtures                  6.18.3

Import worked:

============================= test session starts =============================
platform win32 -- Python 3.6.6, pytest-7.0.1, pluggy-1.0.0

....runs tests

**Comment by cjw296** [comment]
The message given is pretty clear. Testfixtures used to ship with moneypatches for bugs in `unittest.mock` in old versions of Python like 3.6.6, but since Python 3.6 is now [past EOL](https://endoflife.date/python) it no longer does.

You can either install the mock backport, or, much better, upgrade to a supported version of Python.

**Comment by screig** [comment]
Sure I understand that but on pypi it says you support 3.6, hence I raised this issue.

![image](https://user-images.githubusercontent.com/4292074/159158248-bfcf9868-e8eb-49c8-941c-c0e37e143d3e.png)

**Comment by cjw296** [comment]
You _can_ use old, buggy, unsupported-by-upstream versions on Python, yes, but, this time with bold-and-linked, since you appear to have missed it before:

You can either **[install the mock backport](https://pypi.org/project/mock/)**, or, much better, upgrade to a supported version of Python.

**Comment by screig** [comment]
Thanks but the Python version in use is beyond my control. I will limit the requirements file to specify an older version, thanks for your help.
