### ISSUE TITLE
6.18.5 - broken logcapture and tempdir decorator

### ISSUE THREAD

**Issue by tpazderka** [simplistix/testfixtures#174]
After upgrading to `6.18.5`, some of our tests started to fail with the following:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/unittest/mock.py", line 1336, in patched
    return func(*newargs, **newkeywargs)
TypeError: test_cancellation_email_error_log() missing 1 required positional argument: 'log_capture'
```
where the respective test looks as follows:
```
@log_capture('crewatch.views.calendar')                                                                                                                                                                         
@patch('crewatch.views.calendar.send_mail', side_effect=SMTPException('SMTPException test'))          
def test_cancellation_email_error_log(self, mocked_send_mail, log_capture):  
```

Everythyng works if I downgrade to 6.18.4.

Python 3.9.11

**Comment by cjw296** [comment]
I'm afraid I've been unable to reproduce this with Python 3.9.11 and testfixtures 6.18.5.

What versions of which packages do you have installed?
If you're using pip, then the output of `pip freeze` would be ideal.

**Comment by tpazderka** [comment]
The venv is huge, so I will have a look and try to create a MWE.

**Comment by cjw296** [comment]
As a workaround. can you try:
```
from testfixtures.mock import patch
```

**Comment by cjw296** [comment]
Hmm, I'm not sure this is solvable. Only one out of `mock` and `unittest.mock` can ever work at once, so I think you'd need to import patch from `testfixtures.mock`. 

The chance in 6.18.5 meant that your `mock` backport installation was now being used whereas in 6.18.4 it would have been erroneously ignored. I suspect you would have had this issue on earlier versions of testfixtures too.

File another one under the "mock should never have been included in the standard library" banner :-/
