### ISSUE TITLE
Mypy `no_implicit_reexport` x testfixtures

### ISSUE THREAD

**Issue by g-as** [simplistix/testfixtures#178]
Hi,

when enabling `no_implicit_reexport`, mypy displays:

```shell
***.py:98:5: error: "Module testfixtures" does not explicitly export attribute "compare"  [attr-defined]
```

It happens whether `from testfixtures import compare` or `import testfixures; testfixtures.compare(..., ...)`.

According to the [docs](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport), you either have to have in `__init__.py` `from testfixtures.comparison import compare as compare` or `__all__ = (..., "compare", ...)`.

Would you be willing to modify the `__init__.py` in order to address this?

If so, I can draft a PR depending on which way you prefer (either with `__all__` or with `from foo import bar as bar`).

Some context/examples on this particular issue:
https://github.com/python/mypy/issues/10198
https://github.com/konradhalas/dacite/issues/133
https://github.com/konradhalas/dacite/commit/a7834ba2421f6c52be8cd0f787660940deb9fc5b
https://github.com/pallets/quart/commit/c219d9637eddbcfae287b8acfc929be46bd6c829

In any case, a way to disable this `mypy` flag only for `testfixtures` is with:
```toml
[[tool.mypy.overrides]]
module = "testfixtures"
implicit_reexport = true
```

**Comment by cjw296** [comment]
@g-as - Would this problem be resolved if the `py.typed` file if removed from the testfixtures distribution?

I'm afraid I don't have time or energy to appease mypy on the testfixtures project. The type annotations that are there are intended to be helpful documentation and off aid to IDEs...

FWIW, that `no_implicit_reexport` option looks pretty bogus, why are you enabling it?

**Comment by g-as** [comment]
Hi,

from my understanding, `py.typed` just declares to the lib users: "you can look at my annotations", so it's a separate issue. Not even sure it's linked to annotations _per se_.

My use `no_implicit_reexport` is twofold:
- making sure when I want to export a sort of public API through imports in an `__init__.py`, I do it properly. When enabling the flag, it allowed me to fix some missing import. That's the "use case" of this particular issue.
- making sure I'm not importing from a module something that was imported there to be used there, and instead use the direct import path:

```python
a.py

from some_lib import some_stuff

use_some_suff()
```

Works, but not necessarily intended:
```python
b.py

from a import some_stuff
```

If I indeed do want to "reexport" explicitely `some_stuff` for use in `b.py` =>
```python
a.py

from some_lib import some_stuff as some_stuff

use_some_suff()
```

The flag helps tracking that.

In any case, I can totally understand if you do not want to go through with this. As mentioned, the conf allows you to disable some checks for some modules. So feel free to close if you want to leave it at that.

**Comment by cjw296** [comment]
Well, if there had been no `py.typed` file in `testfixtures`, would mypy have complained about this?

**Comment by g-as** [comment]
I think so but let me test.

**Comment by g-as** [comment]
Tested, no `py.typed`, no complaints about reexports.

**Comment by cjw296** [comment]
Okay, so the solution for me is to remove the `py.typed` file from `testfixtures` :-)

**Comment by cjw296** [comment]
Removed in 42b73cf48c1c96df2076335047c6f8f8b219186e and the 7.0.4 release.

**Comment by g-as** [comment]
I'd rather you did not then.

**Comment by g-as** [comment]
LOL.

**Comment by g-as** [comment]
Thanks anyways.

**Comment by cjw296** [comment]
Sorry, but until mypy matures or a better tool comes along that isn't written in Javascript (oh, the irony!), and the minimum Python version I want to support has this mature support, I haven't got the time or energy to appease it.

My experience has been that IDEs, certainly the JetBrains ones, will use the annotations even without the `py.typed` file being present and they also work as documentation, so both of my aims in having annotations present are met.

Should anyone (@asqui ?) be interested in putting a PR together which makes everything happy, and without a hard dependency on the typing-extensions package, I'd definitely try and get it merged.
