### ISSUE TITLE
ShouldWarn option for disregarding order of warnings

### ISSUE THREAD

**Issue by stinovlas** [simplistix/testfixtures#184]
I'd like to use `ShouldWarn` decorator to compare list of warnings disregarding their order. I imagined it could be done like this:

```python
import warnings
from testfixtures import SequenceComparison as S, ShouldWarn

with ShouldWarn(S(UserWarning("X"), UserWarning("Y"), ordered=False)):
    warnings.warn(UserWarning("Y"))
    warnings.warn(UserWarning("X"))
```

However, `ShouldWarn` does not accept `SequenceComparison`. And it also doesn't offer `ordered` kwargs, which would allow us to disregard order. When I do this, the code fails, as it should:

```python
import warnings
from testfixtures import ShouldWarn

with ShouldWarn(UserWarning("X"), UserWarning("Y")):
    warnings.warn(UserWarning("Y"))
    warnings.warn(UserWarning("X"))
```

I see two possible solutions:
1. allow passing of `SequenceComparison` objects directly to `ShouldWarn`
2. add `ordered` kwarg to `ShouldWarn` (default `True`, to maintain the current behaviour)

I'm willing to submit a PR, if we agree on the proper solution.

**Comment by cjw296** [comment]
I'd like to see this happen and great if you're up for working on it!

> However, ShouldWarn does not accept SequenceComparison

What happens when you try?

This feels like less API change, so maybe the way to go?

**Comment by stinovlas** [comment]
If you run the first code example I provided, it outputs this:

```
Traceback (most recent call last):
  File "/home/jmusilek/mwe/testfixtures/test.py", line 4, in <module>
    with ShouldWarn(S(UserWarning("X"), UserWarning("Y"), ordered=False)):
  File "/home/jmusilek/mwe/testfixtures/venv/lib/python3.11/site-packages/testfixtures/shouldwarn.py", line 55, in __exit__
    compare(self.expected, actual=[wm.message for wm in self.recorded])
  File "/home/jmusilek/mwe/testfixtures/venv/lib/python3.11/site-packages/testfixtures/comparison.py", line 758, in compare
    raise AssertionError(message)
AssertionError: sequence not as expected:

same:
[]

expected:
[<C:testfixtures.comparison.SequenceComparison(failed)>wrong type</>]

actual:
[UserWarning('Y'), UserWarning('X')]
```

This is because of `ShouldWarn.__init__`:

```python
class ShouldWarn(warnings.catch_warnings):
    def __init__(self, *expected: WarningOrType, **filters):
        super(ShouldWarn, self).__init__(record=True)
        self.expected = [C(e) for e in expected]
        self.filters = filters

    ...

    def __exit__(self, exc_type, exc_val, exc_tb):
        ...
        compare(self.expected, actual=[wm.message for wm in self.recorded])
```

The key element is `[C(e) for e in expected]`. `SequenceComparison` is just one element, which results in `C(S(...))` being compared with list of emmited warnings. It should be `S(C(...), C(...), ...)` instead.

When I went deeper and examined this, I'm not sure how to do such change without breaking the existing behavior. If we went for `ordered` arg on the `ShouldWarn`, that would be easier to implement although it may complicate the the error messages a bit (just because we would be comparing with `SequenceComparison` rather than plain `list`). The proposed interface would look like this:

```python
with ShouldWarn(UserWarning("X"), UserWarning("Y"), ordered=False):
    warnings.warn(UserWarning("Y"))
    warnings.warn(UserWarning("X"))
```

If we used `ordered=True` (or ommited the argument), the error would look like this:
```
<SequenceComparison(ordered=True, partial=False)(failed)>
same:
[]

expected:
[
<C:builtins.UserWarning(failed)>
attributes differ:
'args': ('X',) (Comparison) != ('Y',) (actual)
</C:builtins.UserWarning>,
 <C:builtins.UserWarning>args: ('Y',)</>]

actual:
[UserWarning('Y'), UserWarning('X')]
</SequenceComparison(ordered=True, partial=False)> (expected) != [UserWarning('Y'), UserWarning('X')] (actual)
```

Compare with current error message:

```
AssertionError: sequence not as expected:

same:
[]

expected:
[
<C:builtins.UserWarning(failed)>
attributes differ:
'args': ('X',) (Comparison) != ('Y',) (actual)
</C:builtins.UserWarning>,
 <C:builtins.UserWarning>args: ('Y',)</>]

actual:
[UserWarning('Y'), UserWarning('X')]
```

Not great, not terrible. I could also only create `SequenceComparison` inside `ShouldWarn` only when `ordered=False`. That way, the current behavior would stay 100% the same, even the error messages. We'd just add a new option. This change would be fairly minimal. I'll prepare a PR and we'll see what you think of it.

**Comment by cjw296** [comment]
Released in https://pypi.org/project/testfixtures/7.2.0/
