### ISSUE TITLE
Popen deprecation warning

### ISSUE THREAD

**Issue by neilmillard** [simplistix/testfixtures#186]
testfixtures/popen.py:1: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
    import pipes

only pipes.quote() is used... but that's just an alias for shlex.quote()

**Comment by cjw296** [comment]
Which versions of Python do you see this warning?

**Comment by neilmillard** [comment]
Python 3.11.5

**Comment by cjw296** [comment]
Thanks for the fix, although you can save yourself a lot of pain by just disabling deprecation warnings of all flavours...
