### ISSUE TITLE
Support test_date or other test date / time functions as decorators

### ISSUE THREAD

**Issue by SEJeff** [Simplistix/testfixtures#25]
Something like [this library](https://pypi.python.org/pypi/freezegun). As a test writer, this is much nicer syntax even though the current method isn't terrible.

**Comment by cjw296** [comment]
I certainly like the idea, it'd basically be syntactic sugar around a Replacer() and test_date*.

The reality, though, is that without a pull request, I'm unlikely to get to it :'(

**Comment by cjw296** [comment]
Closing as no action in a few months, please feel free to re-open with a pull request...
(the one-shot `Replace()` context manager has come along since this was raised, and makes things a little cleaner, the old `@replace()` decorator does this for whole test methods.)
