### ISSUE TITLE
Internal uses of compare() should specify expected/actual

### ISSUE THREAD

**Issue by asqui** [Simplistix/testfixtures#26]
`log.check()` and other internal calls to `compare()` should take advantage of the new feature in 4.4.0 and specify expected/actual arguments for clearer error messages.

**Comment by cjw296** [comment]
With log.check(), I'd agree.
What other ones are you thinking of?

This is one where a pull request would probably make a big difference...

(Sorry, off re-writing Mush at the moment, is that still in use where I left it or has it been ripped out?)
