### ISSUE TITLE
Cannot set default return for mock Popen

### ISSUE THREAD

**Issue by nebulans** [Simplistix/testfixtures#39]
I've got cases I'm testing where using MockPopen is really handy, but I don't want to specify the exact command in my tests.

One attempted workaround is to replace `MockPopen.commands` with a defaultdict, but this doesn't work as the command matcher tests `if cmd not in self.commands:`.  defaultdict instances return `False` here for items that have not previously been accessed.

The solution I've ended up using is to replace `MockPopen.commands` with a `MagicMock`

```python
popen = MockPopen()
popen.commands = MagicMock()
popen.commands.__contains__.return_value = True
popen.commands.__getitem__.return_value = (b'out', b'err', 0, 1234, 1)
```

This clearly isn't a very nice approach.

I can see two obvious approaches - one would be to add a method `set_default()` to `MockPopen` which would work in a simiar way to `set_command()`.  The other (less nice) way would be to change the command matcher to directly attempt attribute access, and catch and re-raise a `KeyError`.  This would allow a defaultdict-based approach to work.

I'm happy to work up a pull request if it's likely to get accepted.

**Comment by cjw296** [comment]
It sounds like you're after a non-strict mode that does a `.get()` instead of a `__getitem__`.

Can you tell me a bit more about the use case?
What will be returned for `self.stdout, self.stderr, self.returncode, pid, poll` if nothing has been explicitly specified?

**Comment by nebulans** [comment]
The use case is for situations where I don't know or want to specify the full command that will be called - maybe it's very long, contains some dynamic components I don't want to mock or simply isn't what I'm trying to test.

In these cases I'd like to be able to explicitly set a default `stdout, stderr, returncode, pid, poll` for any command called that doesn't match something in the commands dict.  If I haven't set a default, I'd expect a `KeyError` to be raised as currently.

**Comment by cjw296** [comment]
Hey, @nebulans, any chance you could take a look at that pull request out?
I'd like to get a release out, but I want to make sure that change to `MockPOpen` meets your needs!

**Comment by nebulans** [comment]
Perfect, thanks.
