### ISSUE TITLE
merge in pyjack functionality

### ISSUE THREAD

**Issue by cjw296** [Simplistix/testfixtures#4]
A placeholder to think about merging in @cart0113 's pyjack functionality:

https://github.com/cart0113/pyjack

**Comment by cjw296** [comment]
Hmm, believe it or not, I've been thinking about this over the years.
I've come to the conclusions that replacing everywhere might well be very very inefficient (think of something like datetime, or another primitive type that's used lots) and so I'm going to close this off.

**Comment by asqui** [comment]
Hmmm, have you done any performance testing or is this just a gut feeling? It's an opt-in behaviour so even if it's slow I don't see what the problem is? You only get it if you specifically ask for it.

**Comment by cjw296** [comment]
Gut feeling. Imagine replacing datetime everywhere in a large code base (like the one you work on!) every time you run each of, say, 10,000 tests ;-)

But yes, still happy to accept a pull request with tests...
