### ISSUE TITLE
Please add license to this repo

### ISSUE THREAD

**Issue by scottvrosenthal** [Simplistix/testfixtures#44]
Something like https://github.com/boto/boto3/blob/develop/LICENSE

In order for the team I'm on to get repos approved for internal use it has to have a license file.

Thanks!

**Comment by cjw296** [comment]
See the "license" link on http://testfixtures.readthedocs.io/en/latest/?

That links to: https://github.com/Simplistix/testfixtures/blob/master/docs/license.txt

...which appears to be what you're asking for.

**Comment by scottvrosenthal** [comment]
Good deal thanks!

**Comment by cjw296** [comment]
Also see 814149e438da106d49fa92d3585e9c1a54a266a3
