### ISSUE TITLE
Primary docs

### ISSUE THREAD

**Issue by jakirkham** [Simplistix/testfixtures#45]
There seem to be two sources for docs. They are listed below. Which should be preferred?

* http://pythonhosted.org/testfixtures/ (on PyPI)
* http://testfixtures.readthedocs.io/en/latest/ (from repo)

cc @ChrisBarker-NOAA

**Comment by cjw296** [comment]
I'd suggest readthedocs is the primary, as they have nicer layout. 
They docs are released in lockstep to bloth places, though...
