### ISSUE TITLE
TempDirectory.compare fails if path ends in a /

### ISSUE THREAD

**Issue by chriscz** [Simplistix/testfixtures#46]
This is due to code in TempDirectory.actual that assumes the path argument does not end in a **/**. I am in the process of creating a pull request.

**Comment by chriscz** [comment]
I just realised that there will be more issues if ends in multiple separators, such as path='source///'

**Comment by cjw296** [comment]
I'm not sure there's a cause to support stupid users ;-)

What happens in the current code base if you use a path that ends in a slash?

**Comment by chriscz** [comment]
Here's an example from my tests:

```
expected:
('docs/',
'docs/file.pdf',
'music/',
'music/awesome/',
'music/awesome/song.mp3',
'other/',
'directories/')
actual:
('directories/',
'docs/',
'music/',
'ocs/file.pdf',
'other/',
'usic/awesome/',
'usic/awesome/song.mp3')

```

**Comment by cjw296** [comment]
where's the code that generated that output?

**Comment by chriscz** [comment]
Here's a snippet. I doubt you'd want to run it, since it's part of a project I'm working on. I did include tests in the pull request

```python
def test_noargs():
    with TempDirectory() as d:
        os.chdir(d.path)
        filetypes = {
            '.*\\.pdf$': 'docs/'
        }

        to_sort = 'source/'

        to_make = ['source/file.pdf']

        initialize_dir(d, filetypes, to_make)

        args = [to_sort, '--filetypes', 'filetypes.py']
        pysorter.main(args)

        # --- compare sorted
        expected = ['docs/', 'docs/file.pdf', 'other/', 'directories/']

        d.compare(expected=expected, path=to_sort)
```
