### ISSUE TITLE
pypi landing page links to outdated docs

### ISSUE THREAD

**Issue by wimglenn** [Simplistix/testfixtures#48]
https://pypi.python.org/pypi/testfixtures landing page is currently at 4.13.1 but has two links pointing at older versions of the docs.  Can you update them to point at http://testfixtures.readthedocs.org/ instead?

No PR because I'm not sure how to fix this, pythonhosted.org gets no mention in setup.py or anywhere else in the repo that I could see..

**Comment by cjw296** [comment]
Unfortunately, I have no control over this. It's a PyPI thing, generate by the templates of the Python software. Please raise with them...

**Comment by wimglenn** [comment]
One workaround I have seen other people use is to put up an index.html with a 301 redirect 
(you need access to the pypi account to do this)

**Comment by wimglenn** [comment]
I can't access it, but I think this is the correct link.  You just prepare a zip file with an index.html 
https://pypi.python.org/pypi?:action=pkg_edit&name=testfixtures

**Comment by cjw296** [comment]
Can you craft me an index.html and paste the content on here?

**Comment by cjw296** [comment]
(I would say "make me a zip", but I don't trust you! ;-))

**Comment by wimglenn** [comment]
```
<html>
  <head>
    <title>TestFixtures documentation</title>
    <meta http-equiv="refresh" content="0;URL='https://testfixtures.readthedocs.io/'" />
  </head>
  <body>
    <p>This page has moved to a <a href="https://testfixtures.readthedocs.io/">
      TestFixtures on Read the Docs</a>.</p>
  </body>
</html>

```

Would you like me to wipe your bum for you too?  ;) 
Save it to `index.html`, zip it, upload on the link I've mentioned earlier.  
I did a test run on http://www.pythonhosted.org/djangorestframework-queryfields/ and it worked...  :beer:

**Comment by cjw296** [comment]
Bonus points: one that works for all my packages ;-)

ie: redirects from https://pythonhosted.org/$1 to $1.readthedocs.org...

**Comment by wimglenn** [comment]
Not sure if possible on pypi.  I only know how to do it with js.  Hire a front-end dev?   :it:   :laughing:

**Comment by wimglenn** [comment]
```
<html>
    <head>
        <script type="text/javascript">
            var packagename = window.location.pathname.split('/')[1]
            window.location.href = '//' + packagename + '.readthedocs.org/'
        </script>
        <title>Page Redirection</title>
    </head>
    <body>
        Current documentation is hosted at <a href='https://readthedocs.org/'>Read the Docs</a>.
    </body>
</html>
```

**Comment by cjw296** [comment]
Yeahbut, not sure it'll help. Looks like the Travis job is still succeeding in uploading the docs somewhere:

https://travis-ci.org/Simplistix/testfixtures/jobs/172616047#L655

@dstuft, any idea why that didn't update https://pythonhosted.org/testfixtures?

**Comment by wimglenn** [comment]
Hmm, what's the problem now?  Can't you just once-off upload the redirect using pypi gui and let it sit there?  (well, upload once-per-project) 
Then the CI doesn't need to update anything at pythonhosted.org

**Comment by cjw296** [comment]
What concerns me is that pypi is telling the CI that the upload is successful...

**Comment by cjw296** [comment]
Nice, done!
