### ISSUE TITLE
log_capture decorator doesn't reset the captured logs if ran twice (Testcase subclass)

### ISSUE THREAD

**Issue by mlabonte** [Simplistix/testfixtures#49]
Here is a way to reproduce the problem:

    import logging
    import unittest
    from testfixtures import log_capture

    class MyTestA(unittest.TestCase):
        a = 33
        
        @log_capture()
        def test_logs_if_a_smaller_than_44(self, logs):
            logger = logging.getLogger()
            if self.a < 44:
                logger.info('{} is smaller than 44'.format(self.a))

            logs.check(
                ('root', 'INFO', '{} is smaller than 44'.format(self.a)),
            )

    class MyTestB(MyTestA):
        a = 2

    if __name__ == '__main__':
        unittest.main()

The result is:

    .F
    ======================================================================
    FAIL: test_logs_if_a_smaller_than_44 (__main__.MyTestB)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "F:\git\rdv_matchmaking\.tox\rdv3.0.8\lib\site-packages\testfixtures\utils.py", line 39, in wrapping
        return wrapped(*args,**kw)
      File "test.py", line 16, in test_logs_if_a_smaller_than_44
        ('root', 'INFO', '{} is smaller than 44'.format(self.a)),
      File "F:\git\rdv_matchmaking\.tox\rdv3.0.8\lib\site-packages\testfixtures\logcapture.py", line 136, in check
        recursive=False
      File "F:\git\rdv_matchmaking\.tox\rdv3.0.8\lib\site-packages\testfixtures\comparison.py", line 385, in compare
        raise AssertionError(message)
    AssertionError: sequence not as expected:

    same:
    ()

    first:
    (('root', 'INFO', '2 is smaller than 44'),)

    second:
    (('root', 'INFO', '33 is smaller than 44'),
     ('root', 'INFO', '2 is smaller than 44'))

    ----------------------------------------------------------------------
    Ran 2 tests in 0.002s

    FAILED (failures=1)

**Comment by cjw296** [comment]
I would say that your use cases is an odd one:

- having test cases on a base class often ends up not doing quite what you want
- making assertions based on a dynamic string makes me sad

**Comment by cjw296** [comment]
4.13.2 is now out with the fix.
