### ISSUE TITLE
No licence file

### ISSUE THREAD

**Issue by LostArchives** [Simplistix/testfixtures#50]
Hello,
I saw that there wasn't a licence file in your project so I suggest to add it :)

**Comment by cjw296** [comment]
You didn't bother looking very far ;-)

https://github.com/Simplistix/testfixtures/blob/master/docs/license.txt

**Comment by cjw296** [comment]
See 814149e438da106d49fa92d3585e9c1a54a266a3 for what I was asking you to do in the PR.
