### ISSUE TITLE
Error "fixture 'capture' not found" with pytest on Python 3.4 and 3.6

### ISSUE THREAD

**Issue by andy-maier** [Simplistix/testfixtures#65]
Hi,
We started migrating the testcases of our project from unittest to pytest, and see the following error on Python 3.4 and 3.6:

```
platform linux -- Python 3.6.2, pytest-3.2.3, py-1.4.34, pluggy-0.4.0
rootdir: /media/share/Projects/zhmcclient/repos/python-zhmcclient, inifile:
plugins: cov-2.5.1
collected 1 item

test_pt.py E

==================================================== ERRORS =====================================================
________________________________________ ERROR at setup of Test2.test_2 _________________________________________
file /media/share/Projects/zhmcclient/repos/python-zhmcclient/try/logcapture/test_pt.py, line 7
      @log_capture(level=logging.DEBUG)
      def test_2(self, capture):
E       fixture 'capture' not found
>       available fixtures: cache, capfd, capsys, cov, doctest_namespace, monkeypatch, pytestconfig, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

The most simple source file reproducing this error, is:

```
import logging
import pytest  # not used here, but is actually used in the real life testcase
from testfixtures import log_capture

class Test2(object):

    @log_capture(level=logging.DEBUG)
    def test_2(self, capture):
        pass
```

We use a virtualenv, and the Python package versions of some relevant packages (in this Python 3.6 environment) are:

```
decorator (4.1.2)
mock (2.0.0)
pytest (3.2.3)
pytest-cov (2.5.1)
testfixtures (5.2.0)
```

This fails on Python 3.4 and 3.6. The same source file succeeds on Python 2.7. Python 3.5 is not currently tested in our CI runs.
Travis logs from our project for these Python environments are here:
https://travis-ci.org/zhmcclient/python-zhmcclient/builds/286095482
It fails and succeeds in the same way on Windows. Appveyor logs are here:
https://ci.appveyor.com/project/leopoldjuergen/python-zhmcclient/build/1.0.1145

As a comparison, the following unittest-based source file (with code that corresponds to the pytest-based file shown above) runs fine in all of these Python versions:

```
import logging
import unittest
from testfixtures import log_capture

class Test1(unittest.TestCase):

    @log_capture(level=logging.DEBUG)
    def test1(self, capture):
        pass
```

Note: I do understand that the testfixtures project no longer supports Python 3.4, but that does not seem to be the problem because it fails with the same symptom on Python 3.6.

**Comment by cjw296** [comment]
Interesting.

As a workaround, I'd suggest using a pytest fixtures instead:

```python
import logging
import pytest  # not used here, but is actually used in the real life testcase
from testfixtures import LogCapture

@pytest.fixture()
def capture():
    with LogCapture() as log:
        yield log

class Test2(object):

    def test_2(self, capture):
        pass
```

Does that work?

**Comment by cjw296** [comment]
Okay, so there's nothing testfixtures can reasonably do about the behaviour of pytest here.
I'd suggest using pattern above and move your `capture()` fixture to a `conftest.py` somewhere that all your tests will pick it up form.

I'm going to add some warning to the docs, but closing this issue...

**Comment by andy-maier** [comment]
Hi Chris. Thanks for providing this workaround!!
It works locally with Python 3.6, and also on Travis with 3.4 and 3.6.
