### ISSUE TITLE
Possible to only check for message type, ignoring message text?

### ISSUE THREAD

**Issue by choldgraf** [Simplistix/testfixtures#66]
I'd like to check if a warning is triggered, without explicitly checking for the message text. Is there a way to do this?

**Comment by cjw296** [comment]
Simplistix Google group would be best for this discussion, but why wouldn't you want to check for the warning text?

**Comment by choldgraf** [comment]
Sometimes I just wanna check for the type of warning instead of the full message text (e.g. if it's a long warning). Also in this specific case I was running into annoying cases where tests on both python2 and 3 meant I had to use two different test warning messages, since strings are handled slightly differently.

**Comment by cjw296** [comment]
Yeah, the latter I tend to handle with just:

```python
def test_something(self):
    if PY2:
        message='...'
    else:
        message='...'
    ...
```

I think you might be able to get what you want using a comparison object as follows:

```python
from testfixtures import Comparison as C, ShouldWarn

def test_something(self):
    with ShouldWarn() as warnings:
        ...
    compare(warnings.recorded, expected=[C(YourWarningHere)])
