### ISSUE TITLE
ShouldRaise buggy with Django's ValidationError

### ISSUE THREAD

**Issue by wimglenn** [Simplistix/testfixtures#75]
```
>>> from testfixtures import ShouldRaise
>>> from django.core.exceptions import ValidationError
>>> with ShouldRaise(ValidationError("d'oh")):
...     raise ValidationError("d'oh")
... 
AssertionError: ValidationError([u"d'oh"]) raised, ValidationError([u"d'oh"]) expected, attributes differ:
  error_list:[ValidationError([u"d'oh"])] != [ValidationError([u"d'oh"])]
```

**Comment by cjw296** [comment]
I think you're casting the "buggy" aspersion in the [wrong direction](https://github.com/django/django/blob/a2e97abd8149e78071806a52282a24c27fe8236b/django/core/exceptions.py#L94-L137).

Here's some code from a codebase you may be working with that deals with this bullshit:

```python
class ShouldRaiseValidationError(ShouldRaise):
    """Allow testing ValidationError for specific messages"""
    def __init__(self, *messages):
        ShouldRaise.__init__(self, ValidationError)
        self.messages = messages

    def __exit__(self, *args):
        ShouldRaise.__exit__(self, *args)
        compare(self.messages, self.raised.messages)
        return True
```

**Comment by cjw296** [comment]
Should I add the snippet above to `testfixtures.django`?

**Comment by wimglenn** [comment]
Why not just make `ShouldRaise` work the "one obvious way"?  i.e., we detect if django is installed, and if so special-case handling for `ValidationError` instances.

**Comment by wimglenn** [comment]
mehh... I agree their exception is kinda naff, but Django is a thing and not going away any time soon.  `ShouldRaiseValidationError` in the `testfixtures.django` submodule would be a welcome addition, but adding it directly to `ShouldRaise` would be even more welcome  :)

**Comment by asqui** [comment]
Pardon me for butting in. What is special about the django ValidationError that makes it not work with `__eq__`?

**Comment by cjw296** [comment]
@asqui - check out this [wonderful code](https://github.com/django/django/blob/a2e97abd8149e78071806a52282a24c27fe8236b/django/core/exceptions.py#L94-L137). Non-django-specific changes that deal with this very welcomely received. If not, I'll chuck `ShouldRaiseValidationError` in `testfixtures.django`.

**Comment by cjw296** [comment]
![](https://4.bp.blogspot.com/-nHclZwYXMM4/WJ9KNgHdmvI/AAAAAAAACLk/DIyZb6FGm0MIwvd4o6DZza05wvT-kmLNwCLcB/s1600/Baldrick%2Bcunning%2Bplan.jpg)

**Comment by cjw296** [comment]
Closing this off, we can track on the PR.
