### ISSUE TITLE
@log_capture() doesn't play nice with other decorators

### ISSUE THREAD

**Issue by rhelms** [Simplistix/testfixtures#76]
Considering the following:

```
class MyTestTestCase(unittest.TestCase):

    @log_capture()
    def test_log_capture_only(self, log_capture):
        self.assertIsInstance(log_capture, LogCaptureForDecorator)

    @log_capture()
    @patch('apps.wideband.manager.order.OrderManager')
    def test_patch_and_log(self, mock, log_capture):
        self.assertIsInstance(log_capture, LogCaptureForDecorator)
        self.assertIsInstance(mock, MagicMock)

    @patch('apps.wideband.manager.order.OrderManager')
    @log_capture()
    def test_log_then_patch(self, log_capture, mock):
        self.assertIsInstance(log_capture, LogCaptureForDecorator)
        self.assertIsInstance(mock, MagicMock)
```
The following error is generated:

```
Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/testfixtures/utils.py", line 42, in wrapping
    return wrapped(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
TypeError: test_patch_and_log() takes exactly 3 arguments (2 given)

Failure
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/usr/local/lib/python2.7/dist-packages/testfixtures/utils.py", line 42, in wrapping
    return wrapped(*args, **kw)
  File "/opt/source/apps/wideband/tests/managers/test_order.py", line 106, in test_log_then_patch
    self.assertIsInstance(log_capture, LogCaptureForDecorator)
AssertionError: <MagicMock name='OrderManager' id='139896440938384'> is not an instance of <class 'testfixtures.logcapture.LogCaptureForDecorator'>)
```

This particular test case was tacked on to the end of a WIP file, so the line numbers won't quite match up.

The first test is fine.
The second test is not populating an argument for `log_capture`.
The third test actually has the order of the types swapped around.

When doing tests that have multiple patches, functionality has been that the `@patch` nearest the `def` appears first in the argument list. I would expect that the same applies here.

Using 
* Python 2.7
* Django 1.10.5
* mock 2.0.0
* testfixtures 5.4.0

**Comment by rhelms** [comment]
My workaround is to use the context method but it would be nice to use the decorator.

**Comment by cjw296** [comment]
What test runner are you using? Is it pytest per chance?

**Comment by rhelms** [comment]
Good question. I had assumed that because I was using the unittest module included with Django that it would be a unittest runner. However, I'm just using the runner that comes with PyCharm Professional that is used with unittest TestCases.

I'll check first thing in the morning (in about 10 or so hours)

**Comment by rhelms** [comment]
There's a bit of a chain of test runners that are used. At the core is the django.test.runner.DiscoverRunner which uses the unittest.TextTestRunner by default.

However, I have a couple of layers on top of that.

The first layer (working from the inner layer) is xmlrunner.extra.djangotestrunner.XMLTestRunner which overrides run_suite() to run xmlrunner.XMLTestRunner, which in turn overrides unittest.TextTestRunner to produce XML output.

The second and top most layer is a custom override of the build_suite() to exclude specific apps.

Neither of these two layers should alter how a unittest.TestCase is run, unless there's a fundamental issue with unittest.TestCase tests and the decorator.

**Comment by cjw296** [comment]
The problem here was both with mock and testfixtures, I'm not 100% my solution will have less problems in the long term, but it's worth a shot!

**Comment by rhelms** [comment]
That works a treat! Thank you.

**Comment by rhelms** [comment]
Will this be packaged into a 5.4.1 release, or similar sometime soon?

**Comment by cjw296** [comment]
There's a 6.0.0 release coming which will have this in, hopefully within a few days...

**Comment by cjw296** [comment]
6.0.0. is out now :-)
