### ISSUE TITLE
LogCapture.check() should accept regexes for checking log messages

### ISSUE THREAD

**Issue by dmwyatt** [simplistix/testfixtures#8]
Often the log message will be dynamic, and if check accepted a regex, then we could avoid having to manually handle the LogRecords to extract the message and regexing against them.

**Comment by xmedeko** [comment]
@cjw296 It would be nice to document it for the `LogCapture.check` method: https://testfixtures.readthedocs.io/en/latest/logging.html#the-check-method

**Comment by cjw296** [comment]
Good pull requests accepted...
