### ISSUE TITLE
v6.0.0 breaks on Python 2.6

### ISSUE THREAD

**Issue by nicolaiarocci** [Simplistix/testfixtures#80]
Since yesterday release our builds on Travis fail when they run under Py26:

original report: https://github.com/pyeve/eve/pull/1128#issuecomment-376791870
travis job: https://travis-ci.org/pyeve/eve/jobs/359239338

Looking at the changelog it doesn't look like py26 support has been officialy dropped.

**Comment by cjw296** [comment]
I'm sorry, but Python 2.6 is no longer supported so you'll have to stick to testfixtures 5.x

**Comment by nicolaiarocci** [comment]
Ah yes, thank you for the prompt reply. I did not look so far back 😄

**Comment by cjw296** [comment]
Also feels like it's worth mentioning that Python 2.6 support endede over 4 years ago:
https://mail.python.org/pipermail/python-dev/2013-September/128287.html

Probably time Eve dropped support for it, is anyone actually using it anymore?

**Comment by nicolaiarocci** [comment]
Well, actually yes. I've been doing some Eve consulting in a University in Northen Europe, and I was surprised to find that they are still using it on Py26. That was a while ago though. Since 0.8 release is close, I might take the chance to either deprecate py26, or drop it altogether. Thanks for the feedback!

**Comment by cjw296** [comment]
It's probably also a good time to throw this out:
https://www.python.org/dev/peps/pep-0373/#maintenance-releases
