### ISSUE TITLE
Problems with @tempdir on Windows

### ISSUE THREAD

**Issue by prsolucoes** [Simplistix/testfixtures#82]
Hi,

My tool EzoRed (ezored.com) is using your library for tests. Specifically the @tempdir annotation.

I have a problem on Windows about permissions. Can you help with the problem?

Bug:
https://github.com/ezored/ezored/issues/21

Full Log:
https://ci.appveyor.com/project/PauloCoutinho/ezored/build/1.0.5

Partial Log:

```
_____________________________ TestCLI.test_debug ______________________________
c:\python36-x64\lib\site-packages\testfixtures\utils.py:95: in patched
    patching.__exit__(*exc_info)
c:\python36-x64\lib\site-packages\testfixtures\utils.py:51: in __exit__
    self.after()
c:\python36-x64\lib\site-packages\testfixtures\tempdirectory.py:81: in cleanup
    rmtree(self.path)
c:\python36-x64\lib\site-packages\testfixtures\rmtree.py:62: in rmtree
    _rmtree(path)
c:\python36-x64\lib\site-packages\testfixtures\rmtree.py:55: in _rmtree
    _waitfor(os.rmdir, path)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
func = <built-in function rmdir>
pathname = 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpwj4pxltw'
waitall = False
    def _waitfor(func, pathname, waitall=False):
        # Perform the operation
>       func(pathname)
E       PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmpwj4pxltw'
c:\python36-x64\lib\site-packages\testfixtures\rmtree.py:13: PermissionError
---------------------------- Captured stdout call -----------------------------
```

**Comment by cjw296** [comment]
I'm afraid I haven't done any development on Windows for 4+ years now, and I don't have access to a Windows development platform, so for this to be resolved, there will need to be some work on your part:

- You need to figure out what process Windows still has a lock on the temp file; does your software use any subprocesses? Have you made sure those subprocesses have terminated by the time `tempdir` attempts its cleanup?

- What's left over in one of the temp directories that's left behind? There's a big list at the end of the test run, have a look inside one of those and it may give you a clue as to what still has a lock

- Be aware that Windows and its filesystems are particularly crappy in this area, see [this code](https://github.com/Simplistix/testfixtures/blob/master/testfixtures/rmtree.py) that I worked into testfixtures back when I still was doing Windows dev.

- If you do find a problem, a PR to testfixtures that added an appveyor run and tests to highlight the problem would be very gratefully received.

Good luck and happy hunting!

**Comment by cjw296** [comment]
No follow up.
