### ISSUE TITLE
Possibility to ignore other warnings in ShouldWarn

### ISSUE THREAD

**Issue by ziima** [Simplistix/testfixtures#83]
I use `ShouldWarn` from time to time, but I found it very difficult to use in cases, when I want to check only one of several warnings that happen to occur.

Consider case:
```python
def deprecated_utility():
    warnings.warn("This utility is deprecated.", DeprecationWarning)

def deprecated_function():
    warnings.warn("This function is deprecated.", DeprecationWarning)
    deprecated_utilitiy()

with ShouldWarn(DeprecationWarning("This function is deprecated.")):
    deprecated_function()
```
This fails because there are two warnings raised instead of only one. I really don't care about the other one, but I only want to check the one I defined. I can bypass that by capturing, but it cumbersome and may be potentially difficult, since warnings may be dependent on the version of python, third party library etc.

I'd like a simple switch, which would ignore all other warnings accidentally captured by `ShouldWarn`.

**Comment by cjw296** [comment]
How would you list to write your test code to express your intention?

**Comment by ziima** [comment]
I'd like to see something like
```
with ShouldWarn(DeprecationWarning("This function is deprecated."), exact_match=False):
    deprecated_function()
```
The current behavior would be with `exact_match=True`.

**Comment by cjw296** [comment]
How about the following?

```
with ShouldWarn(DeprecationWarning, message="This function is deprecated."):
    deprecated_function()
```

With this, I'd add a `**filters` to `ShouldWarn`'s signature, and then use those to construct a warning filter to only record warnings that match you spec.

**Comment by ziima** [comment]
Looks good.

**Comment by cjw296** [comment]
6.1.0 now up on pypi including this.
