### ISSUE TITLE
Problems on Windows

### ISSUE THREAD

**Issue by prsolucoes** [Simplistix/testfixtures#89]
Hi. In my tests im using temporary folder to write/remove data. In my local execution and on TravisCI it is working fine. But on AppVeyor i get a lot of erros:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\tmp07rw3115'
```

I only know that AppVeyor is Windows and on local Windows machine the same errors happen.
What is wrong of test temporary folder on Windows/AppVeyor?

My temporary dir extension is:

```
testfixtures==6.3.0
```

https://ci.appveyor.com/project/PauloCoutinho/ezored/build/1.0.39/job/0wwfixcpuuyq9gxx

**Comment by cjw296** [comment]
@prsolucoes - please follow up or I'll close this as there's been no followup.

**Comment by prsolucoes** [comment]
The problem was not solved, but you can close.
