### ISSUE TITLE
Parallel uses of mock Popen cross-contaminate

### ISSUE THREAD

**Issue by palfrey** [Simplistix/testfixtures#90]
If two calls to Popen are made, and the first is accessed after the second occurs, the outputs of the second feed into the first.

**Comment by cjw296** [comment]
Can you give me an example of where you're hitting this?
(I'm sure there's a unit test in the PR, but interested in the real world case...)

**Comment by palfrey** [comment]
@cjw296 I ran into this while doing some testing of https://github.com/gitpython-developers/GitPython

**Comment by cjw296** [comment]
@palfrey - can you be a bit more specific? Where does GitPython use Popen and how did it end up with two in flight at the same time?

**Comment by palfrey** [comment]
The problem was their AutoInterrupt wrapper class (see https://github.com/gitpython-developers/GitPython/blob/master/git/cmd.py#L340). Basically, they made two Popen calls in one function, wrapped by that, and although they only ever used the first one, then used the second one, when they went out scope the AutoInterrupt `__del__` code kicked in and tried to kill the first one, and then promptly threw an Exception due to a non-zero exit code, which was only expected for the second call...

**Comment by palfrey** [comment]
To be even more specific, I used it in https://github.com/lshift/clincher and https://github.com/lshift/clincher/commit/9fc434510d51fc24d36a381e3c387795f70c8d14 failed like so https://travis-ci.org/lshift/clincher/builds/440137658

**Comment by cjw296** [comment]
Where's the code for `c.check()`? Where are you setting the mock to return `2`?
(sorry, did have a look, but it's not obvious from the diff in your PR)

**Comment by palfrey** [comment]
Returncode: line 141 of https://github.com/lshift/clincher/blob/master/test_commits.py
c.check: line 118 of https://github.com/lshift/clincher/blob/master/check_commits.py

**Comment by cjw296** [comment]
Sorry, let's have this conversation in one place:

> Except that those different behaviours bleed through. If I've got exitcode 1 on the first, and exitcode 2 on the second, after two calls the returncode of both is 2, no matter whether I use callable behaviours or a pair of set_command's.

Please can you give me the simplest possible example of this "bleed through" as that would be a bug that would need to be fixed.

**Comment by palfrey** [comment]
Derived from test I built in the PR. If there wasn't bleed, it should print `1 2`, but it prints `2 2`

```
from testfixtures.popen import MockPopen
from subprocess import PIPE

Popen = MockPopen()
Popen.set_command('a command', b'a', returncode=1)
Popen.set_command('b command', b'b', returncode=2)
process_a = Popen('a command', stdout=PIPE, stderr=PIPE, shell=True)
process_b = Popen(['b', 'command'], stdout=PIPE, stderr=PIPE, shell=True)
print(process_a.wait(), process_b.wait())
```

**Comment by cjw296** [comment]
@palfrey - sorry it's taken me so long to get back to this, got dragged on to other things. You're absolutely correct: `MockPopen` is currently very broken when simulating multiple running processes. I'm working to fix that while retaining backwards compatibility.

**Comment by cjw296** [comment]
Wow, this is turning into a mass of yak shaving: https://bugs.python.org/issue35226

**Comment by cjw296** [comment]
https://github.com/python/cpython/pull/10555 - but will also need to get that into https://github.com/testing-cabal/mock too, and will likely need to have a monkeypatch of some sort in testfixtures as the former of those won't make it into a release most people will be using in a very long time!

**Comment by cjw296** [comment]
@palfrey - apologies for the delay in addressing this, it's now fixed on master. Please let me know if a release would be useful, although I appreciate you've likely worked around this already!

**Comment by palfrey** [comment]
@cjw296 Thanks for that! So, [I've updated my project to use your repo again](https://github.com/lshift/clincher/pull/2), but a release would still be useful, just from a personal preference to avoid using dependencies from git.

**Comment by cjw296** [comment]
@palfrey - 6.4.0 is on PyPI now, let me know if you have any problems!

**Comment by palfrey** [comment]
Excellent, thanks. Just upgraded, and all good.
