### ISSUE TITLE
Any appetite for a DictSubsetComparison?

### ISSUE THREAD

**Issue by asqui** [Simplistix/testfixtures#95]
I've written a `DictSubsetComparison` object that can be used to easily compare an 'actual' dict against a subset of 'expected' values.

For example, this will pass:
```
        compare(
            expected=DictSubsetComparison(dict(x='x')),
            actual=dict(x='x', other='whatever'),
        )
```

This will fail:
```
        compare(
            expected=DictSubsetComparison(dict(x='x')),
            actual=dict(x='y', other='whatever'),
        )
```
It will complain that key `x` did not have the expected value `y` (but without mention of the irrelevant `other='whatever'` item that appears in the actual dict).

Do you have any appetite for this to be contributed to `testfixtures`?

**Comment by cjw296** [comment]
No thanks, I think this is a pretty bad idea.
